### ISSUE TITLE
strange logging

### ISSUE THREAD

**Issue by ward0** [filebot/filebot-node#10]
Whats up with my logging pls?

Locking /volume1/@appstore/filebot-node/filebot.log
Ignore short: /volume1/MOVIES/COUCH/Collide.2016.720p.BluRay.x264-ROVERS[rarbg]/Collide.2016.720p.BluRay.x264-ROVERS.mkv
Ignore short: /volume1/MOVIES/COUCH/The.Girl.on.the.Train.2016.720p.BluRay.x264-SPARKS[rarbg]/The.Girl.on.the.Train.2016.720p.BluRay.x264-SPARKS.mkv
Done ãƒ¾(ï¼ âŒ’ãƒ¼âŒ’ï¼ )ãƒŽ

Keep getting this whole day..

**Comment by rednoah** [comment]
FileBot thinks that the video is less than 10 minutes long (default unless `--def minLengthMS` is set to say otherwise).

What does `filebot -script fn:sysinfo` say?

You may need to install the latest MediaInfo via SynoCommunity:
https://www.filebot.net/forums/viewtopic.php?f=3&t=1802

**Comment by ward0** [comment]
Hey,

I installed mediainfo, got this logging now:

Ignore short: /volume1/MOVIES/COUCH/The.Legend.of.Tarzan.2016.720p.BluRay.x264-SPARKS[rarbg]/The.Legend.of.Tarzan.2016.720p.BluRay.x264-SPARKS.mkv
Done ãƒ¾(ï¼ âŒ’ãƒ¼âŒ’ï¼ )ãƒŽ
Locking /volume1/@appstore/filebot-node/filebot.log
Fetch subtitles for [/volume1/MOVIES/COUCH/The.Legend.of.Tarzan.2016.720p.BluRay.x264-SPARKS[rarbg]]
Get [Dutch] subtitles for 1 files
Looking up subtitles by hash via OpenSubtitles
Fetching [Dutch] subtitles [The Legend of Tarzan (2016).srt] from [OpenSubtitles]
Failed to download The Legend of Tarzan (2016).srt: Server returned HTTP response code: 525 for URL: https://dl.opensubtitles.org/en/download/src-api/vrf-19b00c58/sid-4kjtYpHXQnCSzofIBMTIbkZ6Hfe/file/1955322479.gz
Looking up subtitles by name via OpenSubtitles
Fetching [Dutch] subtitles [The.Legend.of.Tarzan.2016.1080p.BluRay.x264-SPARKS.srt] from [OpenSubtitles]
Failed to download The.Legend.of.Tarzan.2016.1080p.BluRay.x264-SPARKS.srt: Server returned HTTP response code: 525 for URL: https://dl.opensubtitles.org/en/download/src-api/vrf-19e10c64/sid-4kjtYpHXQnCSzofIBMTIbkZ6Hfe/file/1955384789.gz
No matching subtitles found: /volume1/MOVIES/COUCH/The.Legend.of.Tarzan.2016.720p.BluRay.x264-SPARKS[rarbg]/The.Legend.of.Tarzan.2016.720p.BluRay.x264-SPARKS.mkv

**Comment by ward0** [comment]
This is the info you requested:


root@server:~# filebot -script fn:sysinfo
FileBot 4.7.7 (r4678)
JNA Native: 4.0.1
MediaInfo: 0.7.73
Apache Commons VFS: [zip, rar]
Chromaprint: java.io.IOException: Cannot run program "fpcalc": error=2, No such file or directory
Extended Attributes: OK
Script Bundle: 2017-01-05 (r470)
Groovy: 2.4.7
JRE: Java(TM) SE Runtime Environment 1.8.0_91
JVM: 32-bit Java HotSpot(TM) Client VM
CPU/MEM: 1 Core / 247 MB Max Memory / 10 MB Used Memory
OS: Linux (arm)
Package: SPK
Data: /volume1/@appstore/filebot/data/root
uname: Linux server 3.2.40 #8451 Wed Jan 4 00:29:54 CST 2017 armv7l GNU/Linux synology_armada370_213j
Done ヾ(＠⌒ー⌒＠)ノ

**Comment by ward0** [comment]
This is my script:

filebot -script fn:suball /volume1/MOVIES/COUCH --lang nl -non-strict --def maxAgeDays=30 -get-subtitles 'subtitles=nld' 'pushbullet=********' --log all --log-file '/volume1/@appstore/filebot-node/filebot.log' >> '/volume1/@appstore/filebot-node/1460194139938.log' 2>&1

Has been working until the last update.

**Comment by ward0** [comment]
seems to have resolved itself since that mediainfo install:

Fetch subtitles for [/volume1/MOVIES/COUCH/The.Legend.of.Tarzan.2016.720p.BluRay.x264-SPARKS[rarbg]]
Get [Dutch] subtitles for 1 files
Looking up subtitles by hash via OpenSubtitles
Fetching [Dutch] subtitles [The Legend of Tarzan (2016).srt] from [OpenSubtitles]
Export [The Legend of Tarzan (2016).srt] as [SubRip / UTF-8]
Writing [The Legend of Tarzan (2016).srt] to [The.Legend.of.Tarzan.2016.720p.BluRay.x264-SPARKS.nld.srt]
Done ãƒ¾(ï¼ âŒ’ãƒ¼âŒ’ï¼ )ãƒŽ

**Comment by rednoah** [comment]
Installing MediaInfo seems to have solved the problem.
