### ISSUE TITLE
Filebot-node: "command not found"

### ISSUE THREAD

**Issue by Simon-LJ** [filebot/filebot-node#11]
Hey!

I have been using the FileBot Amc for a long time now and it's great! Thank you for that, first of all! :)

I have recently acquired a Synology DS216+II. So far everything seems to be running smoothly, but I am stuck in the FileBot Node. It won't seem to run.
I have installed the Unofficial Java Installer, the FileBot and of course the FileBot Node. It won't run and it gives me an Error window:

<img width="260" alt="screen shot 2017-02-15 at 20 04 26" src="https://cloud.githubusercontent.com/assets/25802226/22990593/ff0d7ae2-f3b9-11e6-897b-9750c74a5f3b.png">

I have checked port 5452/5453, nothing seems to be wrong there. Here's the log, with the "command not found" at line 28:

<img width="782" alt="screen shot 2017-02-15 at 19 57 32" src="https://cloud.githubusercontent.com/assets/25802226/22990629/209915d6-f3ba-11e6-9d35-3dafd6620c16.png">

Thanks in advance!
Simon-LJ

**Comment by rednoah** [comment]
FileBot Node requires FileBot and NodeJS.

**Comment by Simon-LJ** [comment]
Thank you for your help! :)
The NodeJS had not installed correctly. Uninstalled and then reinstalled.
Everything now works perfectly! :)

Thanks (Y)
