### ISSUE TITLE
Synology DSM 6.1 

### ISSUE THREAD

**Issue by chigy110** [filebot/filebot-node#12]
Hello, will there be an update for fileBot Node to support Synology DSM 6.1?

In the Paket-Centre the Paket-Status is offline, if you start it anyway it drops an Error called "Error"

Thanks in before

**Comment by rednoah** [comment]
What does the Log say?

**Comment by chigy110** [comment]
thanks for your reply, I fixed it by reinstalling the paket via paket center.
Thanks alot
