### ISSUE TITLE
filebot-node 0.2.3 not starting on Syn DS213j

### ISSUE THREAD

**Issue by ward0** [filebot/filebot-node#13]
Hey,

service is not starting in package center.

filebot service is ok.

no logging in package center.
and no logging found in filebot-node folder.

Any ideas?

**Comment by rednoah** [comment]
Have you tried uninstall and reinstalling the package?

**Comment by ward0** [comment]
@rednoah  I did not do that yet.. I wanted to inform you first.

**Comment by rednoah** [comment]
Doing all the generic troubleshooting steps would definitely help narrow down the issue. ;)

**Comment by rednoah** [comment]
And?

**Comment by ward0** [comment]
I didn't have time to test yet.. i will let you know.
