### ISSUE TITLE
Custom port is not obeyed by the /filebot endpoint

### ISSUE THREAD

**Issue by pironic** [filebot/filebot-node#15]
I have defined a custom port via the `-e FILEBOT_NODE_HTTP_PORT='####'` command in my docker run command but the /filebot/ url is still forwarding requests to the default 5453 port. Naturally all of these will end up 404.

**Comment by pironic** [comment]
for context it is defined in /filebot/app.json

`"server":{"port":{"http":5452,"https":5453},`

**Comment by rednoah** [comment]
Well, that does put us in a bind, because the client web app is completely static, so it can't be configured dynamically, other than by talking to the server, for which it'll need to know the port in advance.

I guess you won't be able to change the port easily.

**Comment by pironic** [comment]
could load the static inital value from the json file to a variable, then allow the variable to be altered via a simple input box on the frontend. 

What ive done as a work around is put the filebot endpoint behind an nginx reverse proxy and intercept the /filebot/app.json file with a static one that has been customized. works great.

**Comment by rednoah** [comment]
Too much work and ExtJS is no fun. I'm happy to accept pull requests though.
