### ISSUE TITLE
Nothing to do

### ISSUE THREAD

**Issue by netzpixel** [filebot/filebot-node#16]
If I start filebot node it doesn't find anything,
If I than copy the command that has been generated into my shell and execute it there, it works.
I reinstalled filebot and searched on the internet for a solution, but there is nothing.

**Comment by rednoah** [comment]
Logs? Commands? Sample data? Sysinfo? Anything to go on here?

Please read https://www.filebot.net/forums/viewtopic.php?f=5&t=1868

**Comment by netzpixel** [comment]
filebot -script 'fn:amc' /volume1/Downloads/notnamed --output /volume1/Downloads/named --action move -non-strict --conflict auto --lang de --def 'music=y' 'unsorted=y' 'clean=y' 'deleteAfterExtract=y' 'excludeList=.excludes' --log all --log-file '/volume1/@appstore/filebot-node/data/filebot.log'

------------------------------------------

Locking /volume1/@appstore/filebot-node/data/filebot.log
Run script [fn:amc] at [Wed Mar 29 22:00:53 CEST 2017]
Parameter: music = y
Parameter: unsorted = y
Parameter: clean = y
Parameter: deleteAfterExtract = y
Parameter: excludeList = .excludes
Argument[0]: /volume1/Downloads/notnamed
Use excludes: /volume1/Downloads/named/.excludes
No files selected for processing
Done ヾ(＠⌒ー⌒＠)ノ
------------------------------------------

[Process completed]

**Comment by netzpixel** [comment]
Sysinfo... Newest DSM 6.1, newest filebot and filebot node... What do you need?

**Comment by netzpixel** [comment]
Logfile:

Run script [fn:amc] at [Wed Mar 29 22:00:53 CEST 2017]
Parameter: music = y
Parameter: unsorted = y
Parameter: clean = y
Parameter: deleteAfterExtract = y
Parameter: excludeList = .excludes
Argument[0]: /volume1/Downloads/notnamed
Use excludes: /volume1/Downloads/named/.excludes
No files selected for processing
Done M-c^M-CM->(M-oM-<M- M-b^M-L^M-RM-c^M-CM-<M-b^M-L^M-RM-oM-<M- )M-c^M-C^M-N

**Comment by rednoah** [comment]
Are there any files in `/volume1/Downloads/notnamed` that are readable to the admin user that filebot is executed as?

FileBot says that it sees an empty folder, so you're probably dealing with a permissions problem, or an actual empty folder.

**Comment by netzpixel** [comment]
Of cause

Am 30.03.2017 um 07:50 schrieb Reinhard Pointner <notifications@github.com<mailto:notifications@github.com>>:


Are there any (readable) files in /volume1/Downloads/notnamed?

**Comment by rednoah** [comment]
Then that probably means that the user that is running FileBot doesn't have directy listing permissions for that folder.

The easiest solution is to log in as admin into DSM (GUI) and then create a new clean folder there.
