### ISSUE TITLE
error in log

### ISSUE THREAD

**Issue by ward0** [filebot/filebot-node#17]
Hey,

Locking /volume1/@appstore/filebot-node/filebot.log
Illegal Argument: java.nio.file.NoSuchFileException: /usr/syno/synoman/webapi/subtitles=nld (subtitles=nld)
Ignore small: /volume1/MOVIES/COUCH/Resident.Evil.The.Final.Chapter.2016.1080p.BluRay.H264.AAC-RARBG/RARBG.mp4
Fetch subtitles for [/volume1/MOVIES/COUCH/Resident.Evil.The.Final.Chapter.2016.1080p.BluRay.H264.AAC-RARBG]
Get [Dutch] subtitles for 1 files
Looking up subtitles by hash via OpenSubtitles
Looking up subtitles by name via OpenSubtitles

Any idea?

**Comment by rednoah** [comment]
This looks strange:
```
Illegal Argument: java.nio.file.NoSuchFileException: /usr/syno/synoman/webapi/subtitles=nld (subtitles=nld)
```

What's the command you're executing?

**Comment by ward0** [comment]
@rednoah : cfr this ticket:

https://github.com/filebot/filebot-node/issues/10

I'm still using the same batch file to start filebot node.

**Comment by rednoah** [comment]
What is the command you're executing that yields the output you posted in your first post?

EDIT:

Educated guess, your command is broken because you're missing a `--def` before your `--def name=value` script parameters.

**Comment by ward0** [comment]
@rednoah, so i need to change my script to?:

filebot -script fn:suball /volume1/MOVIES/COUCH --lang nl -non-strict --def maxAgeDays=30 -get-subtitles 'subtitles=nld' 'pushbullet=********' --log all --log-file '/volume1//filebot.log' >> '/volume1//1460194139938.log' 2>&1

**Comment by rednoah** [comment]
Here's the manual for the `suball` script:
https://www.filebot.net/forums/viewtopic.php?t=5#p8871
