### ISSUE TITLE
Filebotnode package status 'error'(fout) in syno package center

### ISSUE THREAD

**Issue by ward0** [filebot/filebot-node#19]
![image](https://user-images.githubusercontent.com/15545810/28439305-9d3b8946-6da1-11e7-9b43-38c989ce580b.png)

I tought i saw something about a new repo, i pressume thats causing my error fout? Can't see anything wrong in the package error logs and also the filebotnode is still working(logs are showing still subs downloaded.

**Comment by ward0** [comment]
had a 'repair' button in the package center, seems to be all good again?

**Comment by rednoah** [comment]
No idea. Don't know what `Error: Fout` means. You might sometimes need to reinstall after upgrading DSM though.
