### ISSUE TITLE
QNAP package

### ISSUE THREAD

**Issue by zero77** [filebot/filebot-node#2]
Can you make this compatible with QNAP as well.

**Comment by rednoah** [comment]
The generic Linux package should work. Some manual assembly required though.

**Comment by zero77** [comment]
Okay thanks I'll have a look also where do we submit feature requests for FileBot

**Comment by rednoah** [comment]
FileBot Forums => https://www.filebot.net/forums/viewtopic.php?f=6&t=1244

**Comment by rednoah** [comment]
This issue is dead unless somebody wants to join in and help making this happen.

https://twitter.com/filebot_renamer/status/735042594774781952
