### ISSUE TITLE
Rerooting the app on / instead of /filebot/ ?

### ISSUE THREAD

**Issue by elijah** [filebot/filebot-node#20]
Hi there - I'd like to reroot filebot-node so that I can run it on the root of a domain rather than under the /filebot/ pathing.  Yes, yes, I could set up a reverse proxy to remap all of this, but there are various reasons that I'd prefer not to mess with it.

Am I reading correctly that the logic is that such that I could use a FILEBOT_NODE_CLIENT set to / rather than /filebot/ to get this to happen?  I'm reading around in server-nodejs/app.js -- it looks like that trickles down and the PUBLIC_HTML vars get built out of it.

**Comment by rednoah** [comment]
I think you might need to modify `app.js` for that. `FILEBOT_NODE_CLIENT` is the server-side path to the web app files. You want `PUBLIC_HTML` to be `/` which doesn't seem to be configurable right now.

**Comment by elijah** [comment]
I will probably try it tonight and let you know :)
