### ISSUE TITLE
Filebot-Node An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by hellcry37** [filebot/filebot-node#24]
I keep getting this:

Locking /volume1/@appstore/filebot-node/data/filebot.log
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/volume1/@appstore/filebot/jar/groovy.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by rednoah** [comment]
You can ignore that. It's just a warning you get when running code compiled for Java 8 with Java 12.

**Comment by rednoah** [comment]
You can try the latest `4.8.6` `BETA` which is built for Java 12 and thus suppress these messages:
https://get.filebot.net/filebot/BETA/
