### ISSUE TITLE
start needs to be updated for node 8.0

### ISSUE THREAD

**Issue by fallenczar** [filebot/filebot-node#26]
the function max-executable-size is deprecated in node 8.0.0 and above and has been replaced 
 by max_old_space_size.
users trying to run filebot-node on a system with newer node versionget an error stating node -max-executable-size=xx is an invalid option.
if this can be documented it will help new users.

**Comment by rednoah** [comment]
Please paste the console output.

**Comment by fallenczar** [comment]
XXX@YYY:/opt/filebot-node/0.2.8.5$ node -v
v10.16.0
XXX@YYY:/opt/filebot-node/0.2.8.5$ bash start
node: bad option: --max-executable-size=64

**Comment by rednoah** [comment]
Thanks. Fixed with the latest beta.
