### ISSUE TITLE
Signature missing for FileBot Node 0.4.2.1 on Synology 6.2.4

### ISSUE THREAD

**Issue by lordvandal** [filebot/filebot-node#29]
Hi,

Update to FileBot Node 0.4.2.1 on Synology DS918+ with DSM 6.2.4-25556 is failing with error: **Failed to update "FileBot Node". This package does not contain a digital signature.**

Thanks in advance!

**Comment by rednoah** [comment]
> You may need to adjust the `Trust Level` to allow installation of packages published by `Any Publisher`.

https://www.filebot.net/linux/syno.html
