### ISSUE TITLE
DSM 7 - Filebot-node always failed

### ISSUE THREAD

**Issue by dairen** [filebot/filebot-node#30]
hi,

i migrate to DSM 7
with sysinfo from button tools, i have this config

`filebot -script 'fn:sysinfo' --log-file '/var/packages/filebot-node/var/filebot.log'

------------------------------------------

FileBot 4.9.4 (r8757)
JNA Native: 6.1.0
MediaInfo: 21.03
Tools: fpcalc/1.5.0 p7zip/16.02 unrar/5.70 ffprobe/4.1.6
Extended Attributes: OK
Unicode Filesystem: OK
Script Bundle: 2021-08-02 (r761)
Groovy: 3.0.8
JRE: OpenJDK Runtime Environment 16.0.2
JVM: 64-bit OpenJDK 64-Bit Server VM
CPU/MEM: 8 Core / 8 GB Max Memory / 34 MB Used Memory
OS: Linux (amd64)
HW: Linux NAS_HOME 4.4.180+ #41890 SMP Thu Jul 15 03:42:45 CST 2021 x86_64 GNU/Linux synology_v1000_1821+
CPU/MEM: AMD Ryzen Embedded V1500B [MemTotal: 33 GB | MemFree: 29 GB | MemAvailable: 31 GB | SwapTotal: 22 GB | SwapFree: 22 GB]
STORAGE: ext4 [/] @ 947 MB | btrfs [/volume1] @ 9 TB
USER: FileBot
DATA: /var/packages/filebot/var/data/106247
Package: SPK
License: UNREGISTERED
Done ヾ(＠⌒ー⌒＠)ノ

------------------------------------------

[Process completed]`

i have a registered key

but when i launched Execute/Dry Run,
i have this script
`filebot -script 'fn:amc' /volume1/video/_downloads --output /volume1/video --action hardlink -non-strict --order Airdate --conflict auto --lang en --def 'unsorted=y' 'subtitles=fra' 'skipExtract=y' 'exec=synoindex -R {quote folder}' 'seriesFormat=series/{n}/Saison {s.pad(2)}/{n} - {s00e00} - {t}' 'animeFormat=anime/{n}/Saison {s.pad(2)}/{n} - {s00e00} - {t}' 'movieFormat=films/{primaryTitle}.{y}' 'excludeList=.excludes' --apply refresh --log info --log-file '/var/packages/filebot-node/var/filebot.log'
`

and this log
`Run script [fn:amc] at [Tue Aug 31 00:06:22 CEST 2021]
Parameter: unsorted = y
Parameter: subtitles = fra
Parameter: skipExtract = y
Parameter: exec = synoindex -R {quote folder}
Parameter: seriesFormat = series/{n}/Saison {s.pad(2)}/{n} - {s00e00} - {t}
Parameter: animeFormat = anime/{n}/Saison {s.pad(2)}/{n} - {s00e00} - {t}
Parameter: movieFormat = films/{primaryTitle}.{y}
Parameter: excludeList = .excludes
Argument[0]: /volume1/video/_downloads
Use excludes: /volume1/video/.excludes (538)
.
.
.
*list of elements from excludes file*
.
.
.
No files selected for processing
Done ¯\_(ツ)_/¯

------------------------------------------

[Process completed]`

but in your app, it's always failed
and the schedule option show an popin error synology
![image_2021-08-31_002528](https://user-images.githubusercontent.com/3027708/131413768-121ecec3-e607-485c-af29-2acdc5a81457.png)
![image_2021-08-31_002644](https://user-images.githubusercontent.com/3027708/131413868-4abf96c5-897e-4c99-860d-766e8c570bb1.png)

if i remove a file in my excludes file, filebot not rescan the file in my folder

thx for any answers

**Comment by rednoah** [comment]
1. Have you tried rebooting your device?
2. What does the [server-side FileBot Node log](https://www.filebot.net/forums/viewtopic.php?t=11030) say?

**Comment by dairen** [comment]
Hi

After multiples reboot,
I had a success complete task with Execute button 

But the schedule option doesn't work
I have no {x}.args file to create in tasks folder

So I don't use filebot-node-task script but I add the complete command line
Filebot -script..... in the synology scheduler
