### ISSUE TITLE
Docker vulnerabilities

### ISSUE THREAD

**Issue by frankyw** [filebot/filebot-node#31]
Is it possible to get an updated docker image?

A trivy scan on the current latest image shows:
```
rednoah/filebot:node (ubuntu 20.04)
===================================
Total: 359 (UNKNOWN: 0, LOW: 86, MEDIUM: 271, HIGH: 2, CRITICAL: 0)
```

Thanks!

**Comment by rednoah** [comment]
What is `LOW: 86, MEDIUM: 271, HIGH: 2` based on? Presumably, your tool will give you additional information for each potential issue it detected.

**Comment by frankyw** [comment]
Yes, please attached file.
[filebot.txt](https://github.com/filebot/filebot-node/files/8713259/filebot.txt)

**Comment by rednoah** [comment]
Looks like it's all generic warning messages for the various Linux system libraries and system tools. Presumably, none of that is relevant to `FileBot Node` which can run on any operating system.

The official `filebot` docker containers all use `ubuntu:20.04` (i.e. latest LTS) as platform, so the issues listed above will need to be resolved by the Ubuntu people:
https://hub.docker.com/_/ubuntu
