### ISSUE TITLE
Filebot add a sub folder in output destination

### ISSUE THREAD

**Issue by Ritooon** [filebot/filebot-node#34]
Hi there,

I was wondering if it's possible to indicate to Filebot-node to not create subfolder in destination output ? 

If I set "Documents\PersonnalFolder" in output destination, it will always add "TV Shows" or "Movies" subfolder in the destination output and not directly in the folder I targeted.

**Comment by rednoah** [comment]
You can do that, by specifying a custom format that generates the desired destination path:
* https://www.filebot.net/naming.html
* https://www.filebot.net/forums/viewtopic.php?t=215#format

The solution is to use `{ ~plex.id }` as format:
* https://www.filebot.net/forums/viewtopic.php?t=4116#operators

**Comment by Ritooon** [comment]
Thanks a lot for helping !
