### ISSUE TITLE
Not finding subtitle for a movie that is on OpenSubtitle website with same name.

### ISSUE THREAD

**Issue by ward0** [filebot/filebot-node#6]
Hello,

I just installed your program and it found some subs.

But it has to find more :(

thats the logging screenshot , dunno where to find the actual log file.
![image](https://cloud.githubusercontent.com/assets/15545810/14403097/1638b110-fe4b-11e5-97c9-ad91bbbcc30f.png)

It should find a sub because this is OS link : http://www.opensubtitles.org/nl/search/sublanguageid-dut/idmovie-145852

Star.Wars.Episode.VII.The.Force.Awakens.2015.720p.BluRay.x264-Replica this is the file that has been used to make the sub.

my filebot settings:

![image](https://cloud.githubusercontent.com/assets/15545810/14403110/6388759a-fe4b-11e5-9303-c09bfa93b3d8.png)

**Comment by ward0** [comment]
I found the logs.

``
Run script [fn:amc] at [Sat Apr 09 11:30:08 GMT+01:00 2016]
Parameter: ut_label = movie
Parameter: music = y
Parameter: unsorted = y
Parameter: artwork = y
Parameter: subtitles = nld
Parameter: deleteAfterExtract = y
Parameter: pushbullet = *****
Parameter: excludeList = .excludes
Argument: /volume1/MOVIES/COUCH
Creating excludes: /volume1/DUTCH/.excludes
Input: /volume1/MOVIES/COUCH/Star Wars The Force Awakens(2015)/Star.Wars.Episode.VII.The.Force.Awakens.2015.720p.BluRay.x264-Replica.mkv
Input: /volume1/MOVIES/COUCH/Steve.Jobs.2015.720p.BluRay.x264-DRONES[rarbg]/Steve.Jobs.2015.720p.BluRay.x264-DRONES.mkv
Exclude: /volume1/MOVIES/COUCH/Steve.Jobs.2015.720p.BluRay.x264-DRONES[rarbg]/steve.jobs.2015.720p.bluray.x264-drones.jpg
Exclude: /volume1/MOVIES/COUCH/Star Wars The Force Awakens(2015)/rep-starwarstheforceawakens.720p.bluray.x264.jpg
Exclude: /volume1/MOVIES/COUCH/Star Wars The Force Awakens(2015)/Star.Wars.Episode.VII.The.Force.Awakens.2015.720p.BluRay.x264-Replica.nfo
Group: [mov:star wars the force awakens 2015] => [Star.Wars.Episode.VII.The.Force.Awakens.2015.720p.BluRay.x264-Replica.mkv]
Group: [mov:steve jobs 2015] => [Steve.Jobs.2015.720p.BluRay.x264-DRONES.mkv]
Get [Dutch] subtitles for 1 files
Looking up subtitles by hash via OpenSubtitles
No matching subtitles found: /volume1/MOVIES/COUCH/Star Wars The Force Awakens(2015)/Star.Wars.Episode.VII.The.Force.Awakens.2015.720p.BluRay.x264-Replica.mkv
Rename movies using [TheMovieDB]
Stripping invalid characters from new path: Movies/Star Wars: The Force Awakens (2015)/Star Wars: The Force Awakens (2015)
[HARDLINK] Rename [/volume1/MOVIES/COUCH/Star Wars The Force Awakens(2015)/Star.Wars.Episode.VII.The.Force.Awakens.2015.720p.BluRay.x264-Replica.mkv] to [/volume1/DUTCH/Movies/Star Wars The Force Awakens (2015)/Star Wars The Force Awakens (2015).mkv]
Processed 1 files
Fetching movie artwork for [Star Wars: The Force Awakens (2015)] to [/volume1/DUTCH/Movies/Star Wars The Force Awakens (2015)]
Generate Movie NFO: Star Wars: The Force Awakens [140607]
MediaInfoException: Unable to load arm native library libmediainfo.so: Could not initialize class net.filebot.mediainfo.MediaInfoLibrary
Fetching /volume1/DUTCH/Movies/Star Wars The Force Awakens (2015)/poster.jpg => {category: posters, width: 1000, height: 1500, language: en, url: http://image.tmdb.org/t/p/original/vZpB8ezB1IqpxI9rx553TuGwDzJ.jpg}
Fetching /volume1/DUTCH/Movies/Star Wars The Force Awakens (2015)/fanart.jpg => {category: backdrops, width: 1920, height: 1080, language: en, url: http://image.tmdb.org/t/p/original/zQjse0DOewyVYwHHSIUxz0KVFxY.jpg}
Fetching /volume1/DUTCH/Movies/Star Wars The Force Awakens (2015)/clearart.png => {type=hdmovieclearart, id=126615, url=http://assets.fanart.tv/fanart/movies/140607/hdmovieclearart/star-wars-episode-vii-5639b70eecb49.png, lang=en, likes=23}
Fetching /volume1/DUTCH/Movies/Star Wars The Force Awakens (2015)/logo.png => {type=hdmovielogo, id=88346, url=http://assets.fanart.tv/fanart/movies/140607/hdmovielogo/star-wars-episode-vii-545e78ab10aa1.png, lang=en, likes=22}
Fetching /volume1/DUTCH/Movies/Star Wars The Force Awakens (2015)/disc.png => {type=moviedisc, id=122612, url=http://assets.fanart.tv/fanart/movies/140607/moviedisc/star-wars-episode-vii-560558dfaa838.png, lang=en, likes=20, disc=1, disc_type=bluray}
Get [Dutch] subtitles for 1 files
Looking up subtitles by hash via OpenSubtitles
No matching subtitles found: /volume1/MOVIES/COUCH/Steve.Jobs.2015.720p.BluRay.x264-DRONES[rarbg]/Steve.Jobs.2015.720p.BluRay.x264-DRONES.mkv
Rename movies using [TheMovieDB]
Auto-detect movie from context: [/volume1/MOVIES/COUCH/Steve.Jobs.2015.720p.BluRay.x264-DRONES[rarbg]/Steve.Jobs.2015.720p.BluRay.x264-DRONES.mkv]
[HARDLINK] Rename [/volume1/MOVIES/COUCH/Steve.Jobs.2015.720p.BluRay.x264-DRONES[rarbg]/Steve.Jobs.2015.720p.BluRay.x264-DRONES.mkv] to [/volume1/DUTCH/Movies/Steve Jobs (2015)/Steve Jobs (2015).mkv]
Processed 1 files
Fetching movie artwork for [Steve Jobs (2015)] to [/volume1/DUTCH/Movies/Steve Jobs (2015)]
Generate Movie NFO: Steve Jobs [321697]
MediaInfoException: Unable to load arm native library libmediainfo.so: Could not initialize class net.filebot.mediainfo.MediaInfoLibrary
Fetching /volume1/DUTCH/Movies/Steve Jobs (2015)/poster.jpg => {category: posters, width: 1400, height: 2100, language: en, url: http://image.tmdb.org/t/p/original/ahUiUaeOE2lvnOy7srxaUJbbvYv.jpg}
Fetching /volume1/DUTCH/Movies/Steve Jobs (2015)/fanart.jpg => {category: backdrops, width: 1920, height: 1080, language: null, url: http://image.tmdb.org/t/p/original/vRaRQqtLzpd6crGQPegRNnmh1f9.jpg}
Fetching /volume1/DUTCH/Movies/Steve Jobs (2015)/clearart.png => {type=hdmovieclearart, id=137176, url=http://assets.fanart.tv/fanart/movies/321697/hdmovieclearart/steve-jobs-56b71e3a67901.png, lang=en, likes=7}
Fetching /volume1/DUTCH/Movies/Steve Jobs (2015)/logo.png => {type=hdmovielogo, id=126627, url=http://assets.fanart.tv/fanart/movies/321697/hdmovielogo/steve-jobs-5639ec9a80631.png, lang=en, likes=5}
Fetching /volume1/DUTCH/Movies/Steve Jobs (2015)/disc.png => {type=moviedisc, id=128648, url=http://assets.fanart.tv/fanart/movies/321697/moviedisc/steve-jobs-5650521268f32.png, lang=en, likes=8, disc=1, disc_type=bluray}
Sending PushBullet report
Done ãƒ¾(ï¼ âŒ’ãƒ¼âŒ’ï¼ )ãƒŽ
``

**Comment by rednoah** [comment]
The `amc` script will only perform strict hash/tag lookup. It will not perform a name search. You'll have to set up the suball script in intervals yourself for that.
