### ISSUE TITLE
Problem starting node

### ISSUE THREAD

**Issue by dimitrisst** [filebot/filebot-node#9]
Hi guys,
i have a Synology 112j and i have a problem
When i open filebot node i get

![1](https://cloud.githubusercontent.com/assets/25032782/21807413/4306fcbc-d747-11e6-9b04-7dbec17faee2.png)

and when i press execute i get 

filebot -script 'fn:amc' /volume1/download/ --output /volume1/download/ --action duplicate -non-strict --conflict auto --lang en --def 'music=y' 'unsorted=y' 'subtitles=ell' 'deleteAfterExtract=y' 'excludeList=.excludes' --log all --log-file '/volume1/@appstore/filebot-node/data/filebot.log'

------------------------------------------

/usr/local/bin/filebot: line 65: java: command not found
------------------------------------------

[Process error]

any ideas would be appreciated

**Comment by rednoah** [comment]
Have you tried my Java Installer package?
![Unofficial Java Installer](http://i.imgur.com/l2LMBXf.png)
If yes, what does the log say?

**Comment by dimitrisst** [comment]
Thanks for the replay my friend ,
i tried but Unofficial java installer does not work on my machine, not for my  processor.
![1](https://cloud.githubusercontent.com/assets/25032782/21816395/b5edfc14-d768-11e6-9c13-30191d038361.png)

**Comment by rednoah** [comment]
`filebot-node` requires `filebot` which requires `java`.

DS112J only has 128 MB of RAM. You can install Java Embedded manually but `filebot` probably won't work well on that device anyway. You'd need at least 256 MB of memory and even that might not be enough.

**Comment by dimitrisst** [comment]
Ok my friend thak you for your time 👍
